"""chapter navigation and library

Revision ID: 2119b1cc1050
Revises: ea573cb719cc
Create Date: 2026-08-11 10:27:23.261261

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2119b1cc1050'
down_revision: Union[str, None] = 'ea573cb719cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_cache', sa.Column('next_url', sa.String(), nullable=True))
    op.add_column('chapter_cache', sa.Column('prev_url', sa.String(), nullable=True))
    op.add_column('chapter_cache', sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chapter_cache_last_read_at'), 'chapter_cache', ['last_read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_cache_last_read_at'), table_name='chapter_cache')
    op.drop_column('chapter_cache', 'last_read_at')
    op.drop_column('chapter_cache', 'prev_url')
    op.drop_column('chapter_cache', 'next_url')
    # ### end Alembic commands ###
