"""series grouping and reading feedback

Revision ID: 47f87b59525e
Revises: 2119b1cc1050
Create Date: 2026-08-11 10:51:03.763687

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f87b59525e'
down_revision: Union[str, None] = '2119b1cc1050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('followed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_key', name='uq_series_series_key')
    )
    op.create_index(op.f('ix_series_last_read_at'), 'series', ['last_read_at'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_cache_id', sa.Integer(), nullable=True),
    sa.Column('chapter_title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('para_index', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_cache_id'], ['chapter_cache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_chapter_cache_id'), 'feedback', ['chapter_cache_id'], unique=False)
    # Adjusted from the autogenerated version: SQLite cannot ALTER TABLE ... ADD CONSTRAINT,
    # so the foreign key has to go on through a batch (table-rebuild) operation. Doing it this
    # way keeps the migrated schema identical to the ORM models, so future autogenerate runs
    # don't keep re-detecting a missing foreign key.
    with op.batch_alter_table('chapter_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_chapter_cache_series_id'), ['series_id'], unique=False
        )
        batch_op.create_foreign_key(
            'fk_chapter_cache_series_id_series', 'series', ['series_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_cache', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chapter_cache_series_id_series', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chapter_cache_series_id'))
        batch_op.drop_column('series_id')
    op.drop_index(op.f('ix_feedback_chapter_cache_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_series_last_read_at'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
